{'title': 'Minions',
 'url': 'https://www.boxofficemojo.com/title/tt2293640/',
 'release_date': 'Jul 10, 2015',
 'distributor': 'Universal Pictures',
 'rating': 'PG',
 'genre': 'Adventure Animation Comedy Family Sci-Fi',
 'runtime': '1 hr 31 min',
 'budget': '$74,000,000',
 'domestic_total_gross': '$336,045,770',
 'director': 'Kyle Balda, Pierre Coffin',
 'actors': 'Sandra Bullock, Jon Hamm, Michael Keaton, Pierre Coffin',
 'open_wkend_gross': '$115,718,405',
 'widest_release': '4,386',
 'in_release': '161 days'}
