name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run pytest
      - name: Run tests
        run: pytest
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          BLOG_POSTGRES_DBNAME: ${{ secrets.BLOG_POSTGRES_DBNAME }}
          BLOG_POSTGRES_HOST: ${{ secrets.BLOG_POSTGRES_HOST }}
          BLOG_POSTGRES_PASSWORD: ${{ secrets.BLOG_POSTGRES_PASSWORD }}
          BLOG_POSTGRES_USER: ${{ secrets.BLOG_POSTGRES_USER }}
          GA4_MEASUREMENT_ID: ${{ secrets.GA4_MEASUREMENT_ID }}
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
          GTM_ID: ${{ secrets.GTM_ID }}
          METIS_APP_AWS_ACCESS_KEY_ID: ${{ secrets.METIS_APP_AWS_ACCESS_KEY_ID }}
          PORTFOLIO_AWS_ACCESS_KEY_ID: ${{ secrets.PORTFOLIO_AWS_ACCESS_KEY_ID }}
          PORTFOLIO_AWS_SECRET_KEY: ${{ secrets.PORTFOLIO_AWS_SECRET_KEY }}
          UA_TRACKING_ID: ${{ secrets.UA_TRACKING_ID }}
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PW: ${{ secrets.WP_PW }}